config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :cocktails
  get '/cat/:category', to: 'cocktails#category'

  get '/login', to: 'cocktails#login'

  root to: 'cocktails#index' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :check_name, :except => [:login]

  def check_name
    if not params["reboot"].nil?
      session.clear
      redirect_to '/login.html'
    else
    	if session[:requester].nil? or session[:requester].empty?
    		if params["requester"].nil? or params[:requester].empty?
    			redirect_to '/login.html'
    		else
    			p params["requester"]
    			session[:requester] = params["requester"]
    			redirect_to '/'
    		end
      else
        if session[:requester] == 'Govic'
          @is_root = true
        else
          @is_root = false
        end
    	end
    end
  end

  def login
    render layout: 'light'
  end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.where("cocktailtype = 'cocktail'")
    p 'Cocktails : ' + @cocktails.count.to_s
    @virgins = Cocktail.where("cocktailtype = 'virgin'")
    p 'Virgins : ' + @virgins.count.to_s
    @smoothies = Cocktail.where("cocktailtype = 'smoothie'")
    p 'Smoothies : ' + @smoothies.count.to_s
    @others = Cocktail.where("cocktailtype not in ('smoothie', 'virgin', 'cocktail') or cocktailtype IS NULL")
    p 'Others : ' + @others.count.to_s
    @order = Order.new
  end

  # GET /cocktails
  # GET /cocktails.json
  def category
    @category = params[:category]
    @liste = Cocktail.where("cocktailtype = '%s'", @category)
    p 'Cocktail from category ' + @category + ' : ' + @liste.count.to_s
    @order = Order.new
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :description, :picture, :issmoothie, :cocktailtype)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    if not params['done'].nil?
      p 'Order done !'
      o = Order.find(params['done'])
      o.done = 1
      o.save
    end
    @orders = Order.order(created_at: :desc)
  end

  def create
    @order = Order.new(order_params)

      if @order.save
        flash[:success] = "Merci, la commande est prise en compte ! <br /><a href='/orders'>Voir l'attente</a>"
        redirect_to '/'
      else
        render :new 
      end

  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:requester, :cocktail_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(cocktail) do |f| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cocktailtype %>
    <%= f.text_field :cocktailtype %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :issmoothie %>
    <%= f.check_box :issmoothie %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cocktails/_liste.html.erb
<% liste.each_slice(2) do |cocktails_row| %>

  <div class="row">
  
  <% cocktails_row.each do |cocktail| %>


    <div class="col-sm-12 col-md-6">
      <img src="/assets/<%= cocktail.picture %>" alt="<%= cocktail.name %>" class="img-responsive center-block"  />
      <div class="cocktail_name text-center"><h3><%= cocktail.name %></h3></div>
      <div class="cocktail_description text-center"><h4><%= cocktail.description %></h4></div>
      <%= render 'orders/form', order: @order, cocktail_id: cocktail.id %>
      <% if @is_root %>
        <%= link_to 'Show', cocktail %>
        <%= link_to 'Edit', edit_cocktail_path(cocktail) %>
        <%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <br /><br />
    </div>
  <% end %>
  </div>
<% end %>
<br /><br />

app/views/cocktails/category.html.erb
<% if not notice.nil? %>
<div class="row">
  <div class="col-sm-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <h2 class="text-center">Un 'ti "<%= @category %>" ?</h2>
  </div>
</div>

<% if @liste.count > 0 %>
  <%= render 'liste', liste: @liste %>
<% end %>

<br /><br />
<div class="row">
  <div class="col-sm-12">
    <% if @is_root %>
    <%= link_to 'New Cocktail', new_cocktail_path %>
    <% end %>
  </div>
</div>
<br /><br />

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<% if not notice.nil? %>
<div class="row">
  <div class="col-sm-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<% end %>


<% if @cocktails.count > 0 %>
  <h2 class="text-center"> Nos cocktails</h2>
  <%= render 'liste', liste: @cocktails %>
<% end %>

<input type="text" placeholder="code ?" />

<% if @smoothies.count > 0 %>
  <h2 class="text-center"> Nos smoothies</h2>
  <%= render 'liste', liste: @smoothies %>
<% end %>
<% if @virgins.count > 0 %>
  <h2 class="text-center"> Nos "sans alcool"</h2>
  <%= render 'liste', liste: @virgins %>
<% end %>

<% if @is_root %>
  <% if @others.count > 0 %>
    <h2 class="text-center"> Autres</h2>
    <%= render 'liste', liste: @others %>
  <% end %>
<% end %>

<br /><br />
<div class="row">
  <div class="col-sm-12">
    <% if @is_root %>
    <%= link_to 'New Cocktail', new_cocktail_path %>
    <% end %>
  </div>
</div>
<br /><br />

app/views/cocktails/login.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">

            <form action="/">
                <h2>C'est quoi, ton nom ? </h2>
                <input type="text" id="requester" name="requester" />
                <br /><br />
                <input type="submit" value="Allez, on y va, j'ai soif !!!" class="btn btn-default" />
            </form>
        </div>
    </div>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cocktail.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @cocktail.picture %>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/layouts/application.html.erb
<html lang="fr">
<head>
    <title>Cocktails</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
</head>

<body>

    <%= render '/partials/header' %>

    <% flash.each do |key, value| %>
        <br /> <br />
        <div class="container-fluid">
            <div class="alert alert-<%= key %>"><%= value.html_safe %></div>
        </div>
    <% end %>

    <div class="container-fluid"><%= yield %></div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script src="//cdn.rawgit.com/namuol/cheet.js/master/cheet.min.js"
        type="text/javascript"></script>
<script>
cheet('g o v i c', function () {
  alert('Et si on jouait un peu ? Quel est le surnom de Scalou ?');
});
cheet('k r i m z i m', function () {
  alert('Ok, ok. Jusqu\'ici, tout va bien. Mais connaissez-vous aussi le surnom de notre lapin ?');
});
cheet('g o g o', function () {
  alert('Mouais. Pas mal. Et on habite ou ?');
});
cheet('m e y z i e u', function () {
  alert('Bon, c\'est pas mal... On va pouvoir commencer le jeu maintenant... Ah ah ah. \n\nCherchez sur internet, il faut maintenant rentrer le code Konami. Vu que vous avez peut etre pas de fleche, utilisez la premiere lettre (haut donne h, bas donne b, etc...)');
});
cheet('h h b b g d g d b a', function () {
  alert('Voilà ! C\'est bien. Vous avez trouve beaucoup de bonnes reponses. Alors je vous dis tout : dans cette page, il existe un lien cache, qui permet de faire le cocktail de son choix. A vous de le trouver ! \n\nSi vous voulez des indices, trouvez la reponse a l\'enigme suivante : "Où trouve-t-on samedi avant vendredi ?" (attention, ne mettre qu\'un mot)' );
});
cheet('d i c t i o n n a i r e', function () {
  alert('Bien vu ! Le lien se trouve sur une autre page :) Si vous voulez un autre indice, trouvez la reponse a cette enigme : J\'ai quatre fois l\'âge que vous aviez, quand j\'avais l\'âge que vous avez. J\'ai quarante ans, quel âge avez-vous ? (mettez une reponse en lettre, pour eviter la triche ;) si il y a plusieurs mots, ne mettez aucun espace)');
});
cheet('v i n g t c i n q', function () {
  alert('Bravo. Vous etes tres bon en calcul aussi ! Vous avez merite d\'avoir acces au lien magique. Allez au bas de la page ou l\'on voit la liste d\'attente. A gauche. Un lien est cache. Il est masque, mais je suis sur que pour quelqu\'un comme toi, ce n\'est qu\'un tout petit probleme de plus... ');
});
</script>
</body>
</html>

app/views/layouts/light.html.erb
<html lang="fr">
<head>
    <title>Cocktails</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
</head>

<body>
    
    <div class="text-center">
        <h1>Commandez vos cocktails depuis le canapé.</h1>
        <br /><br />
        <div class="container-fluid"><%= yield %></div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order, :html => {:class => 'text-center'}) do |f| %>
    <%= f.hidden_field :requester, :value => session[:requester] %>
    <%= f.hidden_field :cocktail_id, :value => cocktail_id %>
    <%= f.submit 'J\'en veux un', :class => 'btn btn-default btn-transparent oneplease center-block"' %>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>La file d'attente !</h1>

<% @orders.each do |order| %>
	<div class="attente <% if order.done == 1 %>text-right<% end %>">
		<% if order.done == 1 %><s><% end %>
			<%= order.requester %> a commandé un <%= order.cocktail.name %> il y a <%= time_ago_in_words(order.created_at) %>. 
		<% if order.done == 1 %></s><% end %>
		<% if @is_root %>
			<%= link_to 'Fait !', '/orders?done=' + order.id.to_s %>
		<% end %>
	</div>
<% end %>

<br>

<% if @is_root %>
  <%= link_to 'New Order', new_order_path %>
<% end %>

<a style="color:transparent" target="_blank" href="mailto:hellodelu@gmail.com?subject=Je veux un cocktail personnalise !&body=J'ai trouve le lien secret, alors voici le cocktail que je veux maintenant : %0D%0A %0D%0A (ecrire ici le contenu du cocktail, et j'essaierai de le faire, promis !)">Cliquez moi dessus.</a>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @order.requester %>
</p>

<p>
  <strong>Cocktail:</strong>
  <%= @order.cocktail_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Chez Govic</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Toutes les boissons </a></li>
        <li><a href="/cat/cocktail">Nos Cocktails </a></li>
        <li><a href="/cat/smoothie">Nos Smoothies </a></li>
        <li><a href="/cat/virgin">Nos Sans Alcool </a></li>
        <li><a href="/orders" class="btn btn-default visible-xs visible-sm">Liste d'attente</a></li>
        <li><a href="/orders" class="btn btn-default hidden-xs hidden-sm" id="liste_button">Liste d'attente</a></li>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>